# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.2-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.5-alpine-ram

    working_directory: ~/casting_agency

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd backend
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install coveralls
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "./backend/requirements.txt" }}

      - run:
          name: run tests
          command: |
            cd backend
            mkdir test-reports
            . venv/bin/activate
            coverage run -m pytest
            coverage report && coverage xml -o test-reports/coverage.xml
            coveralls
      - store_test_results:
          path: backend/test-reports
      - store_artifacts:
          path: backend/test-reports
            