"""empty message

Revision ID: 6956dbfb55db
Revises: 1910c756e3ee
Create Date: 2019-12-16 10:27:28.437774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6956dbfb55db'
down_revision = '1910c756e3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movieactors_movie_id_fkey', 'movieactors', type_='foreignkey')
    op.drop_constraint('movieactors_actor_id_fkey', 'movieactors', type_='foreignkey')
    op.create_foreign_key(None, 'movieactors', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movieactors', 'actors', ['actor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movieactors', type_='foreignkey')
    op.drop_constraint(None, 'movieactors', type_='foreignkey')
    op.create_foreign_key('movieactors_actor_id_fkey', 'movieactors', 'actors', ['actor_id'], ['id'])
    op.create_foreign_key('movieactors_movie_id_fkey', 'movieactors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
