"""empty message

Revision ID: 919531ce3299
Revises: 6956dbfb55db
Create Date: 2019-12-20 08:38:41.541859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919531ce3299'
down_revision = '6956dbfb55db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('actors', sa.Column('dob', sa.DateTime(), nullable=False))
    op.add_column('actors', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('actors', 'age')
    op.add_column('movies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('movies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'updated_at')
    op.drop_column('movies', 'created_at')
    op.add_column('actors', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('actors', 'updated_at')
    op.drop_column('actors', 'dob')
    op.drop_column('actors', 'created_at')
    # ### end Alembic commands ###
